package main

import (
	"crypto/aes"
	"crypto/cipher"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"strings"
)

// Uploads are encrypted end-to-end in the browser. The server receives, stores
// and serves ciphertext and holds no key material for any file, so there is no
// file encryption or decryption in this package at all — only the geometry of
// the container format (to validate what clients send) and encryption of short
// settings secrets under the application KEK.
//
// Container format, produced and consumed by web/static/e2e.js: 64 KiB
// plaintext chunks, each sealed with AES-256-GCM under a 12-byte nonce of
// 4 zero bytes || big-endian uint64 chunk index. A Go reference implementation
// lives in the tests, where it pins the format against vectors generated by a
// real WebCrypto implementation.

const (
	chunkPlainSize = 64 * 1024
	gcmOverhead    = 16

	secretPrefix = "enc:v1:"

	// How the browser derived the file key. Both modes keep the key entirely
	// client-side; the server can distinguish them but can decrypt neither.
	keyModeE2EURL      = 3 // key only in the URL fragment
	keyModeE2EPassword = 4 // key derived from the share password in the browser;
	// the server stores just a hash of a separately-derived auth token

	encSaltLen = 16
)

// loadFileKEK reads the 32-byte key-encryption key from FILE_ENCRYPTION_KEY
// (hex or base64) or FILE_ENCRYPTION_KEY_FILE. Returns nil when unset.
//
// The KEK no longer protects uploaded files — those arrive already encrypted
// by a key the server never sees. It protects short secrets held in the
// settings table, principally the OIDC client secret.
func loadFileKEK() ([]byte, error) {
	raw := strings.TrimSpace(os.Getenv("FILE_ENCRYPTION_KEY"))
	if path := strings.TrimSpace(os.Getenv("FILE_ENCRYPTION_KEY_FILE")); raw == "" && path != "" {
		b, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read FILE_ENCRYPTION_KEY_FILE: %w", err)
		}
		raw = strings.TrimSpace(string(b))
	}
	if raw == "" {
		return nil, nil
	}
	if b, err := hex.DecodeString(raw); err == nil && len(b) == 32 {
		return b, nil
	}
	if b, err := base64.StdEncoding.DecodeString(raw); err == nil && len(b) == 32 {
		return b, nil
	}
	return nil, errors.New("FILE_ENCRYPTION_KEY must be 32 bytes, hex- or base64-encoded")
}

func newAEAD(key []byte) (cipher.AEAD, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	return cipher.NewGCM(block)
}

// e2eCipherLen returns the exact ciphertext size the chunk format produces for
// a given plaintext size. The upload handler uses it to reject a blob whose
// length cannot be a well-formed container, which is the only statement the
// server can make about a payload it cannot read.
func e2eCipherLen(plain int64) int64 {
	if plain <= 0 {
		return 0
	}
	chunks := (plain + chunkPlainSize - 1) / chunkPlainSize
	return plain + chunks*gcmOverhead
}

// --- small-secret encryption (settings values) ------------------------------

// encryptSecret protects a short string with the KEK. It returns the input
// unchanged only when at-rest encryption is disabled entirely (no KEK, which
// requires the explicit ALLOW_UNENCRYPTED_SECRETS opt-out at startup); any
// cryptographic failure is an error, never a silent plaintext fallback.
func (a *App) encryptSecret(s string) (string, error) {
	if len(a.fileKEK) == 0 || s == "" {
		return s, nil
	}
	aead, err := newAEAD(a.fileKEK)
	if err != nil {
		return "", fmt.Errorf("encrypt secret: %w", err)
	}
	nonce := randomBytes(aead.NonceSize())
	blob := append(nonce, aead.Seal(nil, nonce, []byte(s), nil)...)
	return secretPrefix + base64.StdEncoding.EncodeToString(blob), nil
}

// decryptSecret reverses encryptSecret; unencrypted values pass through.
func (a *App) decryptSecret(s string) (string, error) {
	if !strings.HasPrefix(s, secretPrefix) {
		return s, nil
	}
	if len(a.fileKEK) == 0 {
		return "", errors.New("encrypted setting present but no FILE_ENCRYPTION_KEY configured")
	}
	blob, err := base64.StdEncoding.DecodeString(strings.TrimPrefix(s, secretPrefix))
	if err != nil {
		return "", err
	}
	aead, err := newAEAD(a.fileKEK)
	if err != nil {
		return "", err
	}
	if len(blob) < aead.NonceSize() {
		return "", errors.New("encrypted setting too short")
	}
	plain, err := aead.Open(nil, blob[:aead.NonceSize()], blob[aead.NonceSize():], nil)
	if err != nil {
		return "", err
	}
	return string(plain), nil
}
