package main

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
)

// Uploads are encrypted end-to-end in the browser. The server receives, stores
// and serves ciphertext and holds no key material for any file, so there is no
// file encryption or decryption in this package at all — only the geometry of
// the container format (to validate what clients send) and encryption of short
// settings secrets under the application KEK.
//
// Container format, produced and consumed by web/static/e2e.js: 64 KiB
// plaintext chunks, each sealed with AES-256-GCM under a 12-byte nonce of
// 4 zero bytes || big-endian uint64 chunk index. A Go reference implementation
// lives in the tests, where it pins the format against vectors generated by a
// real WebCrypto implementation.

const (
	chunkPlainSize = 64 * 1024
	gcmOverhead    = 16

	secretPrefix = "enc:v1:"

	// How the browser derived the file key. Both modes keep the key entirely
	// client-side; the server can distinguish them but can decrypt neither.
	keyModeE2EURL      = 3 // key only in the URL fragment
	keyModeE2EPassword = 4 // key derived from the share password in the browser;
	// the server stores just a hash of a separately-derived auth token
	// 5 — the key comes from a post-quantum KEM encapsulation, which is what a
	// DROP needs: the person encrypting and the person decrypting are different
	// people, so no symmetric secret can travel between them. A stranger with
	// the public link encapsulates to the drop's public key and gets a shared
	// secret the owner can recover from the private link and nobody else can —
	// including the uploader's own tab a moment later. The server holds the
	// ciphertext and, as in modes 3 and 4, can decrypt nothing.
	keyModeE2EKEM = 5

	encSaltLen = 16

	// Container format version, stored per file and per batch.
	//
	// 1 — bare chunk stream. Each chunk authenticates itself and nothing else:
	//     no plaintext length, no chunk count, no name or type inside the
	//     authenticated payload. Whole trailing chunks could therefore be
	//     dropped and the rest still verified, and a blob replaced with zero
	//     bytes decrypted to an empty file without a single GCM failure.
	//     Still read, never written — existing shares must keep working.
	// 2 — the same chunk stream, with an authenticated manifest bound into
	//     every chunk as AES-GCM additional data. The manifest names the
	//     protocol version, a client-generated random file id, the owning
	//     batch, the plaintext size, the chunk count and geometry, the file
	//     name and the MIME type. Truncation, substitution, reordering,
	//     renaming and cross-batch moves all fail authentication.
	// 3 — version 2 with that manifest embedded in the stored object:
	//         "PYX3" || uint16be manifestLen || manifest || chunks…
	//     Version 2 authenticated the metadata but kept it in a database column
	//     beside the blob, so the bytes on disk carried no magic, no version and
	//     no way to say what they were. Version 3 makes the object
	//     self-describing. The header needs no MAC of its own: it IS the AAD, so
	//     altering the length or the manifest breaks every chunk, and altering
	//     the magic is refused outright.
	// 4 — version 3 with the file NAME taken out of the manifest:
	//         "PYX4" || uint16be manifestLen || manifest || chunks…
	//     A manifest cannot be encrypted — it is the AAD — so every name in one
	//     was a name the server could read, in its column and in the object's
	//     own header. Version 4 seals the name in a separate blob under a
	//     separate HKDF branch of the share secret (files.enc_name), which the
	//     server stores and cannot open. A listing decrypts names on their own,
	//     without fetching ciphertext; the manifest id is the blob's AAD, so a
	//     name still belongs to exactly one file.
	// 5 — version 4 with the MIME TYPE taken out of the manifest as well:
	//         "PYX5" || uint16be manifestLen || manifest || chunks…
	//     Version 4 sealed the name and left the type, which still told the
	//     server that an account had uploaded eleven 7 MB JPEGs under one link.
	//     A version 5 manifest says nothing about the content at all — version,
	//     id, batch, size and chunk geometry, every one of which is derivable
	//     from the ciphertext the server is already holding. The type joins the
	//     name in the sealed blob, which is padded from that point on so its
	//     length gives away nothing either.
	e2eVersionLegacy = 1
	e2eVersionV2     = 2
	e2eVersionV3     = 3
	e2eVersionV4     = 4
	e2eVersionV5     = 5

	// What new uploads may declare. Older versions are read for as long as their
	// shares live, but nothing may be WRITTEN in a format that hands the server
	// a name or a type: that is the whole point of version 5, and accepting one
	// more version 4 upload would mean one more file the server can describe. A
	// browser holding a cached e2e.js is told to reload rather than indulged.
	e2eMinUploadVersion = e2eVersionV5
	e2eCurrentVersion   = e2eVersionV5

	// A sealed name is 12-byte nonce || AES-GCM(padded body) || 16-byte tag, and
	// from blob version 2 the body is padded to a multiple of encNamePad. Every
	// ordinary name therefore produces exactly encNameExact bytes, and the
	// column says nothing about the length of what it holds.
	encNameNonce = 12
	encNamePad   = 512
	encNameExact = encNameNonce + encNamePad + gcmOverhead
	// Four pad blocks is far more than any file name needs and still small
	// enough that the column cannot be used to store anything else.
	maxEncNameLen = encNameNonce + 4*encNamePad + gcmOverhead

	// --- drops -------------------------------------------------------------
	//
	// The KEM is X-Wing (ML-KEM-768 + X25519, draft-connolly-cfrg-xwing-kem),
	// implemented in web/static/mlkem.js and mirrored in xwing_test.go. None of
	// it runs here: these are lengths, so the server can refuse a malformed blob
	// without ever being able to interpret a well-formed one.
	dropVersionV1      = 1
	dropCurrentVersion = dropVersionV1

	// The public key, and the public key as stored: sealed under a key derived
	// from the PUBLIC link's fragment. Sealing it keeps that link 43 characters
	// long — a 1216-byte key in a URL would not survive being copied, let alone
	// photographed — and means a server that swaps in a key of its own is caught
	// by GCM rather than believed.
	dropPublicKeyLen = 1216
	dropNonceLen     = 12
	dropSealedPKLen  = dropNonceLen + dropPublicKeyLen + gcmOverhead

	// One submission's encapsulation, stored on its batch row.
	dropCiphertextLen = 1120

	// The upload token derived from the public link's fragment. The server keeps
	// SHA-256 of it, exactly as it does for a password share's auth branch, so
	// the capability to write into a drop lives in a fragment the server never
	// receives rather than in a path its access log records.
	dropTokenLen = 32

	// AAD prefixes. The drop's public id binds a sealed public key to one drop;
	// the submission's batch id binds a sealed sender note to one submission.
	dropPKAADPrefix = "pyxis-drop-pk-v1|"
	noteAADPrefix   = "pyxis-note-v1|"

	// A drop's label and the note shown to uploaders are the two strings the
	// server can read, because the uploader has to be shown them before any key
	// exchange has happened. They are bounded so they cannot become storage.
	maxDropLabelLen = 120
	maxDropNoteLen  = 2000

	// A sender's note travels sealed and padded exactly like a file name, so
	// maxEncNameLen and validEncNameLen apply to it unchanged.

	// A manifest is a short JSON object. The ceiling exists so a client cannot
	// make the server store, and every downloader fetch, an arbitrary blob
	// under the name "metadata". It is also well under the uint16 the version 3
	// header length field can express.
	maxManifestLen = 4096

	// Version 3 header: 4-byte magic, then a big-endian uint16 manifest length.
	containerHeaderFixed = 6

	// Length of the client-generated file id: 32 random bytes, base64url.
	manifestIDLen = 43
)

// fileManifest is the authenticated metadata of one end-to-end encrypted file.
//
// The BYTES matter, not this struct. The client seals its chunks against the
// exact bytes it produced, and those bytes are what must come back — so the
// server stores them verbatim, never re-serialises them, and this type exists
// only to validate what arrives and to reject what is inconsistent. Re-encoding
// a manifest, even to an equivalent JSON document, destroys the file.
type fileManifest struct {
	V      int    `json:"v"`
	ID     string `json:"id"`
	Batch  string `json:"batch,omitempty"`
	Size   int64  `json:"size"`
	Chunks int64  `json:"chunks"`
	Chunk  int64  `json:"chunk"`
	Name   string `json:"name"`
	Type   string `json:"type"`
}

// e2eChunkCount returns how many GCM chunks a plaintext of this size occupies.
//
// Version 2 always emits at least one chunk, even for an empty file. That chunk
// has no plaintext, only a tag over the manifest — which is precisely the point:
// without it an empty file would carry no authentication at all, and "replace
// the blob with nothing" would once again be a silently valid empty file.
func e2eChunkCount(plain int64, version int) int64 {
	n := (plain + chunkPlainSize - 1) / chunkPlainSize
	if n < 1 && version >= e2eVersionV2 {
		return 1
	}
	if n < 0 {
		return 0
	}
	return n
}

// containerMagic marks a version 3 object, containerMagicV4 a version 4 one.
// Bytes rather than string constants so a stray edit cannot change their length.
var (
	containerMagic   = []byte{'P', 'Y', 'X', '3'}
	containerMagicV4 = []byte{'P', 'Y', 'X', '4'}
	containerMagicV5 = []byte{'P', 'Y', 'X', '5'}
)

// magicForVersion is the four bytes a container of this version must start with.
func magicForVersion(version int) []byte {
	switch {
	case version >= e2eVersionV5:
		return containerMagicV5
	case version >= e2eVersionV4:
		return containerMagicV4
	default:
		return containerMagic
	}
}

// validEncNameLen reports whether a sealed name has a length the padding scheme
// can actually produce. A blob of any other size was not padded as version 5
// requires, and its length would leak what the padding exists to hide.
func validEncNameLen(n int) bool {
	if n > maxEncNameLen {
		return false
	}
	body := n - encNameNonce - gcmOverhead
	return body >= encNamePad && body%encNamePad == 0
}

// e2eHeaderLen is how many bytes precede the chunk stream. Only version 3 has
// a header; earlier versions start at zero.
func e2eHeaderLen(manifestLen, version int) int64 {
	if version < e2eVersionV3 {
		return 0
	}
	return int64(containerHeaderFixed + manifestLen)
}

// e2eCipherLen returns the exact stored size the container produces for a given
// plaintext size. The upload handler uses it to reject a blob whose length
// cannot be a well-formed container, which is the only statement the server can
// make about a payload it cannot read.
func e2eCipherLen(plain int64, manifestLen, version int) int64 {
	if plain < 0 {
		return 0
	}
	return e2eHeaderLen(manifestLen, version) +
		plain + e2eChunkCount(plain, version)*gcmOverhead
}

// buildContainerHeader returns the bytes a version 3 or 4 object must begin
// with. The server does not create containers; it builds the header to compare
// against what a client uploaded, which is how it refuses an object whose
// embedded metadata disagrees with the manifest sent alongside it.
func buildContainerHeader(manifest []byte, version int) []byte {
	head := make([]byte, containerHeaderFixed+len(manifest))
	copy(head, magicForVersion(version))
	binary.BigEndian.PutUint16(head[4:6], uint16(len(manifest)))
	copy(head[containerHeaderFixed:], manifest)
	return head
}

// verifyContainerHeader reads the version 3 header off the front of an upload
// and checks it against the manifest the request declared, returning the header
// bytes so the caller can write them through to storage.
//
// This is the one structural claim the server can check about a payload it
// cannot read, and it matters: if the embedded manifest and the stored column
// were allowed to diverge, the column would be describing a file that says
// something else about itself, and only the downloader would ever find out.
func verifyContainerHeader(r io.Reader, manifest []byte, version int) ([]byte, error) {
	want := buildContainerHeader(manifest, version)
	magic := magicForVersion(version)
	got := make([]byte, len(want))
	if _, err := io.ReadFull(r, got); err != nil {
		return nil, fmt.Errorf("container header is truncated: %w", err)
	}
	if !bytes.Equal(got[:len(magic)], magic) {
		return nil, fmt.Errorf("not a Pyxis v%d container: bad magic", version)
	}
	if !bytes.Equal(got, want) {
		return nil, errors.New("the manifest embedded in the file does not match the one sent with it")
	}
	return got, nil
}

// parseManifest validates an uploaded manifest against everything the server
// independently knows: the declared plaintext size, the container geometry and
// the batch the upload claims to join. It returns the decoded view; the caller
// keeps and stores the raw bytes.
//
// The server cannot verify the manifest cryptographically — it holds no key —
// but it can refuse one that contradicts the request around it, which stops a
// buggy or hostile client from storing metadata that no downloader could ever
// authenticate.
func parseManifest(raw []byte, plainSize int64, batchID string, version int) (*fileManifest, error) {
	if len(raw) == 0 {
		return nil, fmt.Errorf("manifest is required for an e2e_version %d upload", version)
	}
	if len(raw) > maxManifestLen {
		return nil, fmt.Errorf("manifest is %d bytes, the maximum is %d", len(raw), maxManifestLen)
	}
	var m fileManifest
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, fmt.Errorf("manifest is not valid JSON: %w", err)
	}
	switch {
	case m.V != version:
		// The manifest states the container version it was written for, and it
		// is authenticated; the form field is not. They have to agree, or the
		// server would be storing a row that contradicts the file.
		return nil, fmt.Errorf("manifest declares version %d, but the upload declares %d", m.V, version)
	case len(m.ID) != manifestIDLen:
		return nil, errors.New("manifest id must be 32 random bytes, base64url")
	case m.Size != plainSize:
		return nil, fmt.Errorf("manifest size %d disagrees with plain_size %d", m.Size, plainSize)
	case m.Chunk != chunkPlainSize:
		return nil, fmt.Errorf("manifest chunk size %d, want %d", m.Chunk, chunkPlainSize)
	case m.Chunks != e2eChunkCount(plainSize, version):
		return nil, fmt.Errorf("manifest chunk count %d, want %d",
			m.Chunks, e2eChunkCount(plainSize, version))
	case version >= e2eVersionV4 && m.Name != "":
		// A manifest that still carries a name is a client leaking the very
		// thing these versions exist to hide. Refuse it rather than store it:
		// these bytes are served to every downloader verbatim.
		return nil, errors.New("a version 4 or later manifest must not carry a file name")
	case version < e2eVersionV4 && m.Name == "":
		return nil, errors.New("manifest carries no file name")
	case version >= e2eVersionV5 && m.Type != "":
		return nil, errors.New("a version 5 manifest must not carry a content type")
	case version < e2eVersionV5 && m.Type == "":
		return nil, errors.New("manifest carries no content type")
	case m.Batch != batchID:
		// Both directions matter: a member must name its batch, and a
		// standalone share must not claim one.
		return nil, fmt.Errorf("manifest batch %q does not match the upload's batch %q", m.Batch, batchID)
	}
	if _, err := base64.RawURLEncoding.DecodeString(m.ID); err != nil {
		return nil, errors.New("manifest id is not base64url")
	}
	return &m, nil
}

// loadFileKEK reads the 32-byte key-encryption key from FILE_ENCRYPTION_KEY
// (hex or base64) or FILE_ENCRYPTION_KEY_FILE. Returns nil when unset.
//
// The KEK no longer protects uploaded files — those arrive already encrypted
// by a key the server never sees. It protects short secrets held in the
// settings table, principally the OIDC client secret.
func loadFileKEK() ([]byte, error) {
	raw := strings.TrimSpace(os.Getenv("FILE_ENCRYPTION_KEY"))
	if path := strings.TrimSpace(os.Getenv("FILE_ENCRYPTION_KEY_FILE")); raw == "" && path != "" {
		b, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read FILE_ENCRYPTION_KEY_FILE: %w", err)
		}
		raw = strings.TrimSpace(string(b))
	}
	if raw == "" {
		return nil, nil
	}
	if b, err := hex.DecodeString(raw); err == nil && len(b) == 32 {
		return b, nil
	}
	if b, err := base64.StdEncoding.DecodeString(raw); err == nil && len(b) == 32 {
		return b, nil
	}
	return nil, errors.New("FILE_ENCRYPTION_KEY must be 32 bytes, hex- or base64-encoded")
}

func newAEAD(key []byte) (cipher.AEAD, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	return cipher.NewGCM(block)
}

// --- small-secret encryption (settings values) ------------------------------

// encryptSecret protects a short string with the KEK. It returns the input
// unchanged only when at-rest encryption is disabled entirely (no KEK, which
// requires the explicit ALLOW_UNENCRYPTED_SECRETS opt-out at startup); any
// cryptographic failure is an error, never a silent plaintext fallback.
func (a *App) encryptSecret(s string) (string, error) {
	if len(a.fileKEK) == 0 || s == "" {
		return s, nil
	}
	aead, err := newAEAD(a.fileKEK)
	if err != nil {
		return "", fmt.Errorf("encrypt secret: %w", err)
	}
	nonce := randomBytes(aead.NonceSize())
	blob := append(nonce, aead.Seal(nil, nonce, []byte(s), nil)...)
	return secretPrefix + base64.StdEncoding.EncodeToString(blob), nil
}

// decryptSecret reverses encryptSecret; unencrypted values pass through.
func (a *App) decryptSecret(s string) (string, error) {
	if !strings.HasPrefix(s, secretPrefix) {
		return s, nil
	}
	if len(a.fileKEK) == 0 {
		return "", errors.New("encrypted setting present but no FILE_ENCRYPTION_KEY configured")
	}
	blob, err := base64.StdEncoding.DecodeString(strings.TrimPrefix(s, secretPrefix))
	if err != nil {
		return "", err
	}
	aead, err := newAEAD(a.fileKEK)
	if err != nil {
		return "", err
	}
	if len(blob) < aead.NonceSize() {
		return "", errors.New("encrypted setting too short")
	}
	plain, err := aead.Open(nil, blob[:aead.NonceSize()], blob[aead.NonceSize():], nil)
	if err != nil {
		return "", err
	}
	return string(plain), nil
}
